---
version: "3"

services:
  login:
    container_name: login
    build:
      context: .
      dockerfile: ./docker/login/Dockerfile
    volumes:
      - ./assets:/app/assets
    ports:
      - 7775:7775
