---
version: "3"

services:
  db:
    build: ./docker/postgres
    container_name: db
    restart: always
    volumes:
      - ./db/data:/var/lib/postgres/data
    ports:
     - 5432:5432
    environment:

