---
version: "3"

services:
  mysql:
    container_name: mysql
    build: ./docker/mysql
    restart: on-failure
    volumes:
      - ./data:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
