---
version: "3"

services:
  login:
    container_name: login
    build:
      context: .
      dockerfile: ./docker/login/Dockerfile
    restart: on-failure
    volumes:
      - ./assets:/app/assets
    ports:
      - 7775:7775
  mysql:
    container_name: mysql
    build: ./docker/mysql
    restart: on-failure
    volumes:
      - ./data:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
